flight:
  ros__parameters:
    hold_threshold: 20
    origin_threshold: 10  

    trajectory_step: 0.5
    straight_line_length: 4.0
    arc_radius: 2.0
    
    cruise_speed: 1.5
    lookahead_distance: 1.0
    decel_distance: 1.5
    min_speed: 0.15
